# Generated by Django 5.0.3 on 2024-04-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=30),
        ),
    ]
